apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/eficode-academy/flask-quotes-frontend:release
          name: quotes-flask-frontend
          ports:
            - containerPort: 5000
          resources: {}
          env:
            - name: backend_host
              value: "quote-app-with-database-gcp-backend-svc"
            - name: backend_port
              value: "5000"
