apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: quote-app-with-database-gcp-frontend-
commonLabels:
  app: quote-app-with-database-gcp-frontend
resources:
- frontend-deployment.yml
- frontend-service.yml
- ingress.yml