apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replacements:
- source:
    fieldPath: spec.template.spec.containers.0.image
    kind: Rollout
    options:
      delimiter: ':'
      index: 1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.0.value
    select:
      kind: Rollout

images:
- name: dagandersen/echo-server
  newTag: "v0.1.3-x86"
