apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: echo-server-argo-rollout-
commonLabels:
  app: echo-server-argo-rollout
resources:
- rollout.yml
- service.yml
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml