apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-lets-go
rules:
- apiGroups: ["*"]
  resources: ["deployments", "deployments/scale", "statefulsets", "cronjobs"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-lets-go
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: role-lets-go
  apiGroup: ""
