apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patchesJson6902:
- target:
    version: v1
    kind: Ingress
    name: basic-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "prod.dagandersen.com"