apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-client
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/cloud-infra-deployment
    targetRevision: HEAD
    path: ./echo-client/overlays/env
  syncPolicy:
    automated:
      prune: true