apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server-argo-rollout
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/k8s-ucp-app-gitops
    targetRevision: HEAD
    path: ./echo-server-argo-rollout/overlays/env
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true