apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-database-eficode-aws
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/k8s-ucp-app-gitops
    targetRevision: HEAD
    path: ./example-database-eficode-aws/overlays/env