apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
resources:
- ../../base
- config.yml

replacements:
- source:
    kind: ConfigMap
    fieldPath: data.env
  targets: 
  - select:
      kind: Application
    fieldPaths: 
    - spec.source.path
    options:
      delimiter: '/'
      index: 3
- source:
    kind: ConfigMap
    fieldPath: data.cluster-name
  targets: 
  - select:
      kind: Application
    fieldPaths: 
    - spec.destination.name
